language: node_js
node_js:
  - 10
install:
  - npm install
before_script:
  - ./scripts/start.server.sh
script:
  - npm run test
after_script:
  - ./scripts/down.server.sh

notifications:
  email: false
